# This is file is for development purposes only!

version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/wp-content/themes/wip
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: qwerty
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DEBUG: 1
      WP_DEBUG: 1

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_PASSWORD: qwerty
    volumes:
      - ./mysql:/var/lib/mysql
